steps:
# Build the container image
- name: 'gcr.io/lstm-368609/lstm'
  args: ['build', '-t', 'gcr.io/lstm-368609/lstm', '.']
  options:
  logging: CLOUD_LOGGING_ONLY
# Push the container image to Container Registry
- name: 'gcr.io/lstm-368609/lstm'
  args: ['push', 'gcr.io/lstm-368609/lstm']
  options:
  logging: CLOUD_LOGGING_ONLY
# Deploy container image to Cloud Run
- name: 'gcr.io/lstm-368609/lstm'
  entrypoint: gcloud
  args: ['run', 'deploy', 'lstm', '--image', 'gcr.io/lstm-368609/lstm', '--region', 'us-central1', '--platform', 'managed','--port','80']
  options:
  logging: CLOUD_LOGGING_ONLY
images:
- gcr.io/lstm-368609/lstm