steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lstm-1-369118/lstm-1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lstm-1-369118/lstm-1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'lstm-1', '--image', 'gcr.io/lstm-1-369118/lstm-1', '--region', 'us-central1', '--platform', 'managed','--port','80']
options:
  logging: CLOUD_LOGGING_ONLY    
images:
- gcr.io/lstm-368609/lstm